// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("CSharp.ProjectTemplate")]
[assembly: AssemblyProductAttribute("CSharp.ProjectTemplate")]
[assembly: AssemblyDescriptionAttribute("A short summary of your project")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "CSharp.ProjectTemplate";
        internal const System.String AssemblyProduct = "CSharp.ProjectTemplate";
        internal const System.String AssemblyDescription = "A short summary of your project";
        internal const System.String AssemblyVersion = "1.0.0";
        internal const System.String AssemblyFileVersion = "1.0.0";
    }
}
